# Generated by Django 5.1.4 on 2025-01-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.RemoveField(
            model_name='car',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='car',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=50),
        ),
    ]
