# Generated by Django 5.1.4 on 2025-01-14 16:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_car_color_remove_car_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('wash_type', models.CharField(choices=[('B', 'Basic Wash'), ('D', 'Deluxe Wash'), ('P', 'Premiun Wash')], max_length=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
        ),
    ]
