# Generated by Django 5.1.4 on 2025-01-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_wash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wash',
            options={'ordering': ['-date']},
        ),
    ]
