# Generated by Django 5.1.4 on 2025-01-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessories'),
        ),
    ]
