# Generated by Django 5.1.4 on 2025-01-15 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_car_accessories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accessories',
            new_name='Accessory',
        ),
    ]
