# Generated by Django 5.1.4 on 2025-01-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_accessories_accessory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='accessories',
            field=models.ManyToManyField(related_name='cars', to='main_app.accessory'),
        ),
    ]
